### ISSUE TITLE
Add a Sponsors Page 

### ISSUE THREAD

**Issue by alina-naqvi** [ybashir/pycon_web#13]
We require a Sponsors page addition in the navigation bar.

![add sponsors link](https://user-images.githubusercontent.com/14196678/30863580-d37130e6-a2ea-11e7-821f-ae05b11348cd.png)

Site url:  http://pycon.arbisoft.com/

**Comment by hamza-jutt** [comment]
Provide list of sponsors to be display on page.

**Comment by alina-naqvi** [comment]
For now, only Arbisoft logo will go up on the page.

**Comment by alina-naqvi** [comment]
![sponsors added](https://user-images.githubusercontent.com/14196678/31533967-35ae15be-b00e-11e7-8148-9cb58c2cae59.png)
