### ISSUE TITLE
Gallery page: Image hyperlink icon selection should redirect to a full album of the event.

### ISSUE THREAD

**Issue by alina-naqvi** [ybashir/pycon_web#16]
Gallery Page,
When hovering over any of the featured images in the gallery, the hyperlink icon click should open up an album of the event. We can add some event description in the album's page. 
![redirect to a complete album of the event](https://user-images.githubusercontent.com/14196678/30915283-bf65bb10-a3af-11e7-8f23-64bc87298873.png)

Mezzanine editorial link: http://pycon.arbisoft.com/admin/galleries/gallery/3/change/
Site url: http://pycon.arbisoft.com/gallery/

(Either we can populate the images on the redirected album page or we can link it to our Facebook album page)

**Comment by hamza-jutt** [comment]
Links fixed. Now pointing to facebook album. Though imges need to be updated.

**Comment by alina-naqvi** [comment]
![image click redirects to album](https://user-images.githubusercontent.com/14196678/31535864-1888afc8-b016-11e7-94ee-ec4f206ce26e.png)
