### ISSUE TITLE
Home page slider doesn't seem screen responsive. 

### ISSUE THREAD

**Issue by alina-naqvi** [ybashir/pycon_web#27]
Viewed the home page on Chrome and Microsoft Edge. Both screens showed an empty space on the right. 
PFA
![slider doesn t seem screen responsive](https://user-images.githubusercontent.com/14196678/31425602-6eaa7dc6-ae79-11e7-8e04-c72a01b6ecbe.png)

Site URL : http://pycon.arbisoft.com

@murad-hubib

**Comment by murad-hubib** [comment]
@alina-naqvi I have already pushed this fix yesterday. Right now, home page is getting an error. Let me confirm the change after we get home page up

**Comment by alina-naqvi** [comment]
The screen responsive issue is resolved, but he arrow buttons aren't consistent in placement while sliding through.

**Comment by alina-naqvi** [comment]
Okay so the above comment will get addressed in issue #38. Closing this out.
