### ISSUE TITLE
Home page isn't functional anymore.

### ISSUE THREAD

**Issue by alina-naqvi** [ybashir/pycon_web#28]
![home page isn t functional](https://user-images.githubusercontent.com/14196678/31426909-b29fa952-ae7e-11e7-9a17-cfc965849856.png)

Site URL: http://pycon.arbisoft.com/

@hamza-jutt

**Comment by murad-hubib** [comment]
This is a DB issue and we are getting this fixed in a while

**Comment by alina-naqvi** [comment]
verified!
