### ISSUE TITLE
Need to improve message that appear after registration form and contact email

### ISSUE THREAD

**Issue by alina-naqvi** [ybashir/pycon_web#42]
After the contact form message displayed is 'Your message is received.'
Registration form submission shows 'Your tickets are booked now'
Need to update both messages 
something like  "Thank you! your tickets are booked now, We hope to see you at the event"

**Comment by hamza-jutt** [comment]
@alina-naqvi can you provide the messages for both?

**Comment by alina-naqvi** [comment]
Will provide them shortly.

**Comment by alina-naqvi** [comment]
For Tickets page: "Thank you! your tickets are booked now, We hope to see you at the event"
For Contact page: Thank you for contacting us, someone from the PyCon organizing team will get in touch with you!

Both updated.
