### ISSUE TITLE
Schedule page should redirect to a ‘coming soon’ text 

### ISSUE THREAD

**Issue by alina-naqvi** [ybashir/pycon_web#43]
Currently it displays 'Page not found'

![schedule page](https://user-images.githubusercontent.com/14196678/31536402-e734eee4-b017-11e7-89f2-b1fc56b8eba2.png)

**Comment by hamza-jutt** [comment]
@alina-naqvi Move this to done.

**Comment by alina-naqvi** [comment]
![coming soon text](https://user-images.githubusercontent.com/14196678/31602630-1cdec202-b277-11e7-8625-9f2f26d52391.png)
Verifed!
