### ISSUE TITLE
In event info section 'Tickets' placement is a bit off (towards right)

### ISSUE THREAD

**Issue by alina-naqvi** [ybashir/pycon_web#46]
Site Url: http://pycon.arbisoft.com/
Scroll to the section where event info is displayed.
With the over all placements of icons and text, the last 'Tickets' space is slightly more than the usual. 
PFA 

![fix space issue](https://user-images.githubusercontent.com/14196678/31543210-9480a956-b02e-11e7-93b1-8bf4b3fc0af5.png)

**Comment by murad-hubib** [comment]
it's just an illusion due to less text in the section
