### ISSUE TITLE
Watermark in contact page is overlapping input text when ‘tab’ is used

### ISSUE THREAD

**Issue by alina-naqvi** [ybashir/pycon_web#48]
Site url:  http://pycon.arbisoft.com/contact-us/
Steps to reproduce:
1. Select name field
2. Enter name 
3.Select 'tab' key enter text in email.
Issue: It overlaps the watermark 
PFA

![tab selection overlaps the watermark and texts](https://user-images.githubusercontent.com/14196678/31546656-a61b67d2-b03d-11e7-98ae-1658279b3e5f.png)

**Comment by alina-naqvi** [comment]
Can we add a default cursor in 'name' field when the user lands on Contact page?

**Comment by hamza-jutt** [comment]
This is fixed already in the recent PR. but that hasn't deployed yet.

**Comment by alina-naqvi** [comment]
Will hold on to it, until then.

**Comment by alina-naqvi** [comment]
Fixed!
