### ISSUE TITLE
Sponsor logos are disproportionate

### ISSUE THREAD

**Issue by ybashir** [ybashir/pycon_web#53]
FAST logo looks much bigger than the other two. They should all be proportionately sized.

**Comment by murad-hubib** [comment]
@ybashir every logo is carrying width 200 pixels. The only difference is, other logos have extra space on their sides and fast logo is cropped within the outline.

**Comment by ybashir** [comment]
You can make them proportionate by rescaling and adding some transparent padding to the sides

**Comment by murad-hubib** [comment]
Done

**Comment by alina-naqvi** [comment]
Can we center align the blocks? 
![center align sponsors blocks](https://user-images.githubusercontent.com/14196678/31603602-1acc0a4e-b27a-11e7-8c03-bd6ae0812e55.png)
