### ISSUE TITLE
Update Home Page slider images

### ISSUE THREAD

**Issue by alina-naqvi** [ybashir/pycon_web#6]
Add Pakistan/PyCon event related images in Slider 

Mezzanine Media library link: http://pycon.arbisoft.com/admin/media-library/browse/
Mezzanine editorial link: http://pycon.arbisoft.com/admin/pages/richtextpage/2/change/
Site url : http://pycon.arbisoft.com/

**Comment by murad-hubib** [comment]
@alina-naqvi where I can find event related images?

**Comment by ybashir** [comment]
This should not be "Done" yet. @hamza-jutt @murad-hubib since we still dont have the correct images.

**Comment by alina-naqvi** [comment]
Images updated and verified.
