### ISSUE TITLE
Update Home Page links in Menu Dropdown 

### ISSUE THREAD

**Issue by alina-naqvi** [ybashir/pycon_web#7]
Update all relevant links in menu drop down so that they redirect to their respective functional pages. 

![menu dropdown](https://user-images.githubusercontent.com/14196678/30824815-3211328c-a24a-11e7-94d2-384622a89e9a.png)

Site url : http://pycon.arbisoft.com/

Links required:

- About 
- Blog
- Contact
- Gallery
- Location 
- Schedules
- Speakers
- Sponsors
- Tickets

**Comment by murad-hubib** [comment]
@alina-naqvi can you please group similar items?

**Comment by alina-naqvi** [comment]
About will contain - Blog and Contact. 
The rest are fine separately. 
Just need to add 'schedule' to the list.

**Comment by alina-naqvi** [comment]
Verified!
