### ISSUE TITLE
Update Footer links 

### ISSUE THREAD

**Issue by alina-naqvi** [ybashir/pycon_web#8]
Sort and remove irrelevant links (i.e. Sign-up and Sign-in, Docs etc.)

![update pycon footer links](https://user-images.githubusercontent.com/14196678/30846244-4bbf9a28-a2b0-11e7-8cd7-54b88f521dd9.png)

Site url : http://pycon.arbisoft.com/
(Note: Add a final list of footer links here. 
Make sure all links are functional and get redirected to their respective pages, check urls too.)

**Comment by murad-hubib** [comment]
@alina-naqvi Please update this issue with the links we need actually

**Comment by alina-naqvi** [comment]
- Blog
- Contact us
- Gallery 
- How it works (redirect to About page)
- Sponsors
- Schedule
- Tickets

**Comment by alina-naqvi** [comment]
![footer links updated](https://user-images.githubusercontent.com/14196678/31533916-feccd63e-b00d-11e7-98fd-f35457463cc5.png)
